# Generated by Django 2.1.2 on 2018-10-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Imię')),
                ('surname', models.CharField(max_length=10, verbose_name='Nazwisko')),
                ('information', models.TextField(verbose_name='Informacja do instruktora')),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
