# Generated by Django 2.1.2 on 2018-11-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='information',
            field=models.TextField(null=True, verbose_name='Informacja do instruktora'),
        ),
    ]
