# Generated by Django 2.1.2 on 2018-11-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_auto_20181128_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='information',
            field=models.TextField(blank=True, null=True, verbose_name='Informacja do instruktora'),
        ),
    ]
